In [1]:
import seaborn as sns
import pandas as pd
import plotly.express as px
import numpy as np

In [3]:
data = sns.load_dataset("tips")
data.head(5)

features = data[["total_bill"]]
tip = data["tip"]

from sklearn import linear_model
f = linear_model.LinearRegression(fit_intercept=False)
f.fit(features, tip)

LinearRegression(fit_intercept=False)

In [4]:
data["prediction"] = f.predict(features)
data.head(5)

   total_bill   tip     sex smoker  day    time  size  prediction
0       16.99  1.01  Female     No  Sun  Dinner     2    2.442005
1       10.34  1.66    Male     No  Sun  Dinner     3    1.486188
2       21.01  3.50    Male     No  Sun  Dinner     3    3.019807
3       23.68  3.31    Male     No  Sun  Dinner     2    3.403571
4       24.59  3.61  Female     No  Sun  Dinner     4    3.534367

In [6]:
data["l2_loss"] = (data["tip"] - data["prediction"]) ** 2
data.head(5)

   total_bill   tip     sex smoker  day    time  size  prediction   l2_loss
0       16.99  1.01  Female     No  Sun  Dinner     2    2.442005  2.050638
1       10.34  1.66    Male     No  Sun  Dinner     3    1.486188  0.030211
2       21.01  3.50    Male     No  Sun  Dinner     3    3.019807  0.230585
3       23.68  3.31    Male     No  Sun  Dinner     2    3.403571  0.008756
4       24.59  3.61  Female     No  Sun  Dinner     4    3.534367  0.005720

In [7]:
np.mean(data["l2_loss"])

1.178116115451317

In [8]:
data["l2_loss"].mean()

1.178116115451317

In [9]:
from sklearn.metrics import mean_squared_error
mean_squared_error(tip, data["prediction"])

1.178116115451317

In [10]:
def mse_given_theta(theta):
    return mean_squared_error(data["total_bill"] * theta, tip)

In [11]:
mse_given_theta(0.2)

2.667486278688525

In [12]:
mse_given_theta(0.08)

3.08881276852459

In [13]:
thetas = np.linspace(0.1, 0.2, 100)
thetas

array([0.1       , 0.1010101 , 0.1020202 , 0.1030303 , 0.1040404 ,
       0.10505051, 0.10606061, 0.10707071, 0.10808081, 0.10909091,
       0.11010101, 0.11111111, 0.11212121, 0.11313131, 0.11414141,
       0.11515152, 0.11616162, 0.11717172, 0.11818182, 0.11919192,
       0.12020202, 0.12121212, 0.12222222, 0.12323232, 0.12424242,
       0.12525253, 0.12626263, 0.12727273, 0.12828283, 0.12929293,
       0.13030303, 0.13131313, 0.13232323, 0.13333333, 0.13434343,
       0.13535354, 0.13636364, 0.13737374, 0.13838384, 0.13939394,
       0.14040404, 0.14141414, 0.14242424, 0.14343434, 0.14444444,
       0.14545455, 0.14646465, 0.14747475, 0.14848485, 0.14949495,
       0.15050505, 0.15151515, 0.15252525, 0.15353535, 0.15454545,
       0.15555556, 0.15656566, 0.15757576, 0.15858586, 0.15959596,
       0.16060606, 0.16161616, 0.16262626, 0.16363636, 0.16464646,
       0.16565657, 0.16666667, 0.16767677, 0.16868687, 0.16969697,
       0.17070707, 0.17171717, 0.17272727, 0.17373737, 0.17474747,
       0.17575758, 0.17676768, 0.17777778, 0.17878788, 0.17979798,
       0.18080808, 0.18181818, 0.18282828, 0.18383838, 0.18484848,
       0.18585859, 0.18686869, 0.18787879, 0.18888889, 0.18989899,
       0.19090909, 0.19191919, 0.19292929, 0.19393939, 0.19494949,
       0.1959596 , 0.1969697 , 0.1979798 , 0.1989899 , 0.2       ])

In [14]:
mses = [mse_given_theta(theta) for theta in thetas]
mses

[2.0777683729508194,
 2.0366887534058913,
 1.996569059699077,
 1.9574092918303747,
 1.919209449799786,
 1.8819695336073097,
 1.8456895432529465,
 1.8103694787366964,
 1.7760093400585586,
 1.7426091272185338,
 1.7101688402166224,
 1.678688479052823,
 1.6481680437271375,
 1.6186075342395636,
 1.5900069505901033,
 1.5623662927787565,
 1.5356855608055218,
 1.5099647546704,
 1.4852038743733909,
 1.461402919914495,
 1.4385618912937121,
 1.4166807885110417,
 1.3957596115664843,
 1.37579836046004,
 1.3567970351917082,
 1.3387556357614898,
 1.3216741621693837,
 1.3055526144153906,
 1.2903909924995107,
 1.2761892964217436,
 1.262947526182089,
 1.2506656817805475,
 1.2393437632171185,
 1.2289817704918033,
 1.2195797036046003,
 1.2111375625555103,
 1.2036553473445333,
 1.197133057971669,
 1.1915706944369175,
 1.1869682567402793,
 1.1833257448817533,
 1.1806431588613406,
 1.1789204986790405,
 1.1781577643348538,
 1.1783549558287796,
 1.1795120731608182,
 1.18162911633097,
 1.1847060853392344,
 1.1887429801856118,
 1.193739800870102,
 1.1996965473927048,
 1.206613219753421,
 1.21448981795225,
 1.2233263419891915,
 1.233122791864246,
 1.2438791675774135,
 1.255595469128694,
 1.2682716965180871,
 1.2819078497455934,
 1.2965039288112117,
 1.312059933714944,
 1.3285758644567889,
 1.3460517210367458,
 1.3644875034548163,
 1.3838832117109996,
 1.4042388458052961,
 1.4255544057377052,
 1.4478298915082273,
 1.471065303116862,
 1.4952606405636095,
 1.5204159038484695,
 1.5465310929714433,
 1.5736062079325297,
 1.6016412487317289,
 1.630636215369041,
 1.6605911078444662,
 1.6915059261580032,
 1.7233806703096541,
 1.7562153402994167,
 1.7900099361272936,
 1.824764457793283,
 1.8604789052973851,
 1.8971532786396006,
 1.9347875778199284,
 1.97338180283837,
 2.0129359536949227,
 2.053450030389589,
 2.0949240329223673,
 2.13735796129326,
 2.1807518155022656,
 2.225105595549384,
 2.270419301434615,
 2.316692933157959,
 2.3639264907194146,
 2.4121199741189843,
 2.461273383356666,
 2.5113867184324614,
 2.56245997934637,
 2.614493166098391,
 2.667486278688525]

In [17]:
fig = px.line(x=thetas, y=mses, labels={"x": "Theta", "y": "MSE"}, title="MSE vs Theta")
fig.update_layout(xaxis_title="Theta", yaxis_title="MSE")
fig.show()

In [20]:
import scipy.optimize as opt

In [25]:
opt.minimize(mse_given_theta, x0 = 0.2)

  message: Optimization terminated successfully.
  success: True
   status: 0
      fun: 1.1781161154513287
        x: [ 1.437e-01]
      nit: 1
      jac: [ 2.384e-06]
 hess_inv: [[1]]
     nfev: 6
     njev: 3