In [2]:
import seaborn as sns
import pandas as pd
import plotly.express as px
import numpy as np

In [3]:
data = sns.load_dataset("tips")
data.head(5)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [12]:
features = data[["total_bill"]]
tip = data["tip"]

from sklearn import linear_model
f = linear_model.LinearRegression(fit_intercept=False)
f.fit(features, tip)
f.predict([[100]])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([14.37318953])

In [13]:
f.predict([[74.12]])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([10.65340808])

In [14]:
data["prediction"] = f.predict(features)

In [15]:
data

     total_bill   tip     sex smoker   day    time  size  prediction
0         16.99  1.01  Female     No   Sun  Dinner     2    2.442005
1         10.34  1.66    Male     No   Sun  Dinner     3    1.486188
2         21.01  3.50    Male     No   Sun  Dinner     3    3.019807
3         23.68  3.31    Male     No   Sun  Dinner     2    3.403571
4         24.59  3.61  Female     No   Sun  Dinner     4    3.534367
..          ...   ...     ...    ...   ...     ...   ...         ...
239       29.03  5.92    Male     No   Sat  Dinner     3    4.172537
240       27.18  2.00  Female    Yes   Sat  Dinner     2    3.906633
241       22.67  2.00    Male    Yes   Sat  Dinner     2    3.258402
242       17.82  1.75    Male     No   Sat  Dinner     2    2.561302
243       18.78  3.00  Female     No  Thur  Dinner     2    2.699285

[244 rows x 8 columns]

In [16]:
import plotly.graph_objects as go
fig = go.Figure()
fig.add_trace(go.Scatter(x=data["total_bill"], y=data["tip"], mode='markers', name='Actual Tips'))
fig.add_trace(go.Scatter(x=data["total_bill"], y=data["prediction"], mode='lines', name='Predicted Tips'))
fig.update_layout(title='Total Bill vs Tip', xaxis_title='Total Bill', yaxis_title='Tip')
fig.show()

In [17]:
f.coef_

array([0.1437319])

In [18]:
f.intercept_

0.0